country_code: X
full_language: German
lab_number: 1
language: DE
participant_id: 2
plab: false
ppvt: false
ran: false
random_seed: 123
session_id: 2
stroop_flanker: false
system: Darwin
wcst: true
wmc: false
